---
title: "250_BL_comparisons"
author: "Carlos Blázquez Bondia"
date: '2023-03-22'
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# Group composition at Baseline

This is the very first comparison that should have been done. It wil contain all comparisons, be demographic or clinical at baseline.

## Demographic variables

As this study is an RCT, every referee will ask for the demographic distribution of both groups.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(compareGroups)
source(here::here("code","group_comparisons.R"))
```


```{r input, warning= F, message=FALSE}

mymre <- here::here("data", "filt_mre.rds") %>% 
  readRDS()


metadata <-
  here::here("Metadata") %>% 
    list.files(pattern = "clean_metadata", full.names = T) %>%
  file.info() %>% 
  dplyr::arrange(desc(ctime)) %>% 
  rownames() %>% 
  dplyr::first() %>% 
  read.csv()

```



```{r Overall_comps, warning = F, message = F}
igc<-metar::get_diversity(mymre)@igc
Threshold <-  igc@dataTable %>%
  dplyr::select(SampleID, NumberMappedReads) %>%
  unique() %>%
  summarise(Q = quantile(NumberMappedReads,0.02)) %>% 
  as.numeric()


igc@dataTable %>%
  filter(NumberMappedReads >= Threshold) %>%
  filter(ReadCountReal >= Threshold) %>% ### Get the Mapped Read count (per-sample) just above the threshold
  group_by(SampleID) %>%
  summarise(across(everything(), min)) %>%
  ungroup() %>%
  right_join(., metadata, by = "SampleID") %>% 
  dplyr::filter(time_point == 0) %>% 
  summarise(age = paste(median(age), " [",IQR(age), "]", sep = ""),
            BMI = paste(round(median(BMI, na.rm = T),3), " [",round(IQR(BMI, na.rm = T), 3), "]", sep = ""),
            CD4_nadir = paste(round(median(CD4_nadir, na.rm = T),3), " [",round(IQR(CD4_nadir, na.rm = T), 3), "]", sep = ""),
            VL = paste(round(median(HIV_VL, na.rm = T),3), " [",round(IQR(HIV_VL, na.rm = T), 3), "]", sep = ""),
            richness = paste(round(median(GeneNumber, na.rm = T),3), " [",round(IQR(GeneNumber, na.rm = T), 3), "]", sep = "")) 


```



```{r clinical_comp}




igc_df <- igc@dataTable %>%
  filter(NumberMappedReads >= Threshold) %>%
  filter(ReadCountReal >= Threshold) %>% ### Get the Mapped Read count (per-sample) just above the threshold
  group_by(SampleID) %>%
  summarise(across(everything(), min)) %>%
  ungroup() %>%
  right_join(., metadata, by = "SampleID") %>%
  dplyr::filter(time_point == 0) %>% 
  compareGroups::compareGroups(group ~ age + gender + BMI + HIV_VL + CD4 + CD4_nadir + risk_group + GeneNumber, 
                               data = ., method = 2) %>%
  compareGroups::createTable(x = .) %>%
  compareGroups::export2md()


# igc_df

```

