---
title: "Taxonomy exploration"
author: "Carlos Blázquez Bondia"
date: "3/25/2022"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
library(tidyverse)
library(metar)
library(phyloseq)
```

# Setup

This section will have comments of the step of data entry and anything that may happen here

```{r cars, eval=T, message=F, warning=F}
mymre <- aws.s3::s3readRDS(bucket = "mistral-wp6-advanz4", object ="/metagenome/WMGS/MREObject.rds", region = "eu-west-1") 


# metadata <- get_meta(mymre)
metadata <- here::here("Metadata", "2022_10_05_clean_metadata_LIMS.csv") %>% 
  read.csv() %>% 
  column_to_rownames("SampleID") %>% 
  mutate(SampleID = rownames(.))

CategoricalVariablesDF <- get_cat(mymre)

```


```{r utility_functions, eval=F}

## Any utility function that we do will go here

```



# Phylum Level



```{r Species_level, message=F, warning=F, fig.height=8,fig.width = 8}
# mymre <- metar::metaphlan_barplots(mymre, top_n = 30, tax_level = "Species", save_files = F)

myphyloseq <- get_phyloseq(mymre, type="metaphlan")

abundance <- myphyloseq %>%
  tax_glom(.,"Kingdom") %>%
  otu_table(.) %>%
  t() %>%
  as.data.frame()  %>%
  setNames(tax_table(tax_glom(myphyloseq, "Kingdom"))[,"Kingdom"])




myBarplots <- CategoricalVariablesDF$CategoricalVariable %>%
  set_names() %>%
  map(~ {
    
    dat <- abundance %>%

      rownames_to_column("SampleID") %>%
      right_join(., metadata[,c("SampleID","record_id","time_point", .x)], by="SampleID") %>%
      pivot_longer(., cols=names(abundance)) %>%
      dplyr::rename(taxa = name) %>%
      dplyr::mutate(facet = paste(!!sym(.x), time_point, sep="_")) %>%
      dplyr::rename(cat_var = !!sym(.x)) %>% 
      dplyr::filter(!is.na(cat_var), !is.na(time_point))

    
    plt <- 
      ggplot(dat, aes(x=record_id, y = value, fill = taxa)) +
      facet_grid( time_point ~ cat_var,scales="free_x" ) +
      geom_bar(position = "stack", stat = "identity") +
      theme_bw() +
      theme(strip.text = element_text(size=8, face="bold"),
            strip.background = element_rect(colour = "white"),
            axis.text.x = element_text(angle = 90))
    
  })


myBarplots$group

```




# Additional analysis

here will go any other exploratory analysis on taxonomy that may be needed
