---
title: "Functional exploratory analysis"
author: "Carlos Blázquez Bondia"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---



```{r setup, warning = F, message=F, echo=F}
library(metar)
library(tidyverse)
```



```{r load_metadata_vars,echo = F, eval=T, include=F}


mymre <- aws.s3::s3readRDS("s3://mistral-wp6-advanz4/metagenome/WMGS/MREObject.rds") ### Check consistency between mre.rds(local and S3). You are reading s3 file, here, but in 200_ you are using local
# metadata <- metar::get_metadata(mymre)@metadata_df

metadata <- here::here("Metadata", "2022_09_29_clean_metadata_LIMS.csv") %>% 
  read.csv() %>% 
  column_to_rownames("SampleID") %>% 
  mutate(SampleID = rownames(.))

mymre@metadata@categorical_vals <-  
  here::here("Metadata","CategoricalVariables.txt") %>%
  read.table(., sep="\t") %>%
  setNames(c("CategoricalVariable","PaletteName")) %>%
  as_tibble()

mymre@metadata@metadata_df <-  tibble(metadata)


cat_df <- 
  here::here("Metadata", "CategoricalVariables.txt") %>% 
  read.delim(., header = T)

cat_vector <- cat_df %>% 
  pull(CategoricalVariable)

long_var <- here::here("Metadata", "LongitudinalVariables.txt") %>%
  read.delim(., header = T)  %>% 
  pull(LongitudinalVariable)

link_var <- here::here("Metadata", "LongitudinalVariables.txt") %>%
  read.delim(., header = T)  %>% 
  pull(LinkVariable)

num_var <- here::here("Metadata", "NumericalVariables.txt") %>%
  read.delim(., header = T)  %>% 
  pull(NumericalVariable)


```

```{r update_mre, echo = FALSE,warning= F, message= F}

#### This chunk is for updating the mre internally as new variables come out. Once the final mre is done this chunk will be removed.
devtools::load_all("../WMGSPipeline/")


mymre <- filter_samples(mre = mymre, sample_ids = metadata$SampleID)

mymre@metadata@metadata_df <- as_tibble(metadata)

mymre@metadata@categorical_vals <- here::here("Metadata", "CategoricalVariables.txt") %>% 
  read.delim(., header = T) %>% 
  tibble()

mymre@metadata@numeric_vals <- here::here("Metadata", "NumericalVariables.txt") %>% 
  read.delim(., header = T) %>% 
  tibble()

mymre@metadata@longitudinal_vals <- here::here("Metadata", "LongitudinalVariables.txt") %>% 
  read.delim(., header = T) %>% 
  tibble()


```



```{r extract_tables,message= F, warning=FALSE}
first_table <- 
metar::get_genefunction(mymre, type = "humann", annotation = "kegg") 
# %>% 
#   tidyr::pivot_wider(names_from = "kegg_id", values_from = "CPM")





```

```{r comp_barplots, warning=F, message=F}



first_table %>% 
# metar::get_genefunction(mymre, type = "humann", annotation = "kegg") %>% 
  dplyr::arrange(SampleID) %>% 
  group_by(SampleID) %>% 
  mutate(percent = CPM/sum(CPM)*100) %>%
  mutate(sum_check = sum(percent)) %>% 

  right_join(., metadata[,c("SampleID", "group", "time_point")],by = "SampleID") %>% 
  arrange(SampleID, time_point) %>% 
  filter(!time_point == 24) %>% 
  ggplot(., aes(x = SampleID)) +
  facet_wrap(~group+time_point, scales = "free_x", ncol = 3, nrow = 2)+
  geom_col(aes(fill = kegg_id, y = percent), position = "stack", stat="percent", width = 1) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```


```{r NMDS, message=FALSE, warning=F}

abundance_df <- first_table %>% 
  pivot_wider(names_from = "kegg_id", values_from = "CPM") %>% 
  column_to_rownames("SampleID")

NMDS <- vegan::metaMDS(abundance_df, distance = "bray",k = 2, trymax = 500)
vegan::stressplot(NMDS)


dist_mat <- vegan::vegdist(abundance_df, method = "bray")

adonis_df <- 
  NMDS %>% 
  pluck("points") %>% 
  as.data.frame() %>% 
  rownames_to_column("SampleID") %>% 
  left_join(metadata[,c("SampleID","group", "time_point")], by="SampleID") %>% 
  column_to_rownames("SampleID") %>% 
  vegan::adonis2(dist_mat ~ group, data = .)



nmds_plot <- 
  NMDS %>% 
  pluck("points") %>% 
  as.data.frame() %>% 
  rownames_to_column("SampleID") %>% 
  left_join(metadata[,c("SampleID","group", "time_point")], by="SampleID") %>% 
  ggplot(aes(x=MDS1, y = MDS2)) +
  stat_ellipse(geom="polygon",alpha=0.15,color="black",aes(fill=group),level=0.95) +
  geom_point(aes(color = group)) + 
  theme_bw()
nmds_plot


```


As we can see, no big patterns can be found either at looking at total composition or by NMDS ordination.
