---
title: "Diversity_GeneRichness"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(metar)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(ggpubr)
library(rstatix)
source(file = "RAnalysis/myFunctions.R")

```




```{r load_metadata_vars, eval=T, include=F}
myPath<-here::here()
setwd(myPath)
mymre<-readRDS("DataPackages/mre.rds")

metadata <- metar::get_metadata(mymre)


CategoricalVariablesDF <- metadata@categorical_vals
NumericalVariablesDF <- metadata@numeric_vals
LongitudinalVariablesDF <- metadata@longitudinal_vals





```



```{r get_GeneRichness_Data, echo=FALSE, message=F, warning=F}


igc<-metar::get_diversity(mymre)@igc

# We'll save this number to report the minimum read threshold.
Threshold = igc@dataTable %>%
  summarise(Q = quantile(NumberMappedReads,0.02)) %>%
  as.numeric()

ThresholdTable<-igc@dataTable %>%
  filter(NumberMappedReads >= Threshold) %>%
  group_by(SampleID) %>%
  summarise(across(everything(), min)) %>%
  ungroup() %>%
  left_join(., metadata@metadata_df, by="SampleID")


```

## Longitudinal evolution: LMMs





```{r create_LMM_Function, echo=FALSE}
cat_var<-CategoricalVariablesDF[1,1]
long_var <- LongitudinalVariablesDF$LongitudinalVariable[1]
link_var<-LongitudinalVariablesDF$LinkVariable[1]
id_var<-"SampleID"
t<-LongitudinalVariablesDF$Breakpoints[1]


create_LMM <- function(metadata, num_var, cat_var, long_var, link_var){
  
  myLMM <- metadata@metadata_df %>%
    as.data.frame() %>%
    dplyr::select(link_var = !!sym(link_var),
                  num_var = !!sym(num_var),
                  cat_var = !!sym(cat_var),
                  long_var = !!sym(long_var)) %>%
    dplyr::mutate(cat_var = as.factor(cat_var)) %>%
    myLMM_two.piece.GLMM(Datos = .,
                         Y = "num_var",
                         t = 96,
                         Time = "long_var",
                         Factor = "cat_var",
                         ID = "link_var")
  
  myLMM$
}



# plot_list[[cat_var]][[[num_var]]] <-
  NumericalVariablesDF %>%
  
  dplyr::pull(NumericalVariable) %>%
  purrr::set_names() %>%
  purrr::map( ~ {
    metadata@metadata_df %>%
    create_LMM(., num_var = .x, 
               cat_var = cat_var,
               long_var = long_var)
  }
)


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
